Dev
Parol45/PolyTeX pull request #1
Opened 2020-03-01 20:59 UTC by Parol45

2020-03-01 21:09 UTC, Donutellko commented on src/main/java/ru/test/restservice/MainApplication.java
> +// До сих пор без понятия, что тут происходит
да особо ничего и не происходит
просто запускается спринг бут

2020-03-01 22:14 UTC, Donutellko requested changes

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompileController.java
> +    // Возврат JSON с ошибкой компиляции или pdf
Пиши [JavaDocs](https://www.oracle.com/technetwork/java/javase/documentation/index-137868.html): типа такого:
```suggestion
    /** Возврат JSON с ошибкой компиляции или pdf */
```
Потом сможешь нажать кнопочку и получить доку по всему проекту, видеть описания при листании методов в подсказках, писать в них ссылки на другие куски кода и всякие удобные штуки. Стоит почитать короче

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompileController.java
> +        return new CompilationResult(compRet.contains("! LaTeX Error:") ? compRet : "ok", "test/test.pdf");
При ошибке внутри compileTexFile() должно бросаться исключение. По хорошему оно должно в ExceptionHandler'е ([тут](https://www.baeldung.com/global-error-handler-in-a-spring-rest-api), [тут](https://www.baeldung.com/exception-handling-for-rest-with-spring)) преобразовываться в ответ. Но лучше пока бросай исключение CompilationErrorException с кодом HttpStatus.InternalServerError и в Message пиши этот compRet, типа как [тут](https://www.baeldung.com/spring-mvc-controller-custom-http-status-code#2-returning-status-codes-via-an-exception).
Ну и возвращать из функции надо всё-таки будет path:
`
String path = compileTexFile();
return new CompilationResult(path);
`

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompileController.java
>          return message.toString();
функции compileTexFile и createTexFile должны быть в CompilerService

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    // Функция объединения списков (надо бы вынести в класс utils)
надо бы, да

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    final ArrayList<String> mask = joinLists(maskPic, maskTextFile);
это и всё, что с этим связано, переноси в FileService

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +            return new ResponseEntity<>(HttpStatus.BAD_GATEWAY);
BAD_GATEWAY вроде всё же для других целей
тут INTERNAL SERVER ERROR

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +                isAllowedExtension = isAllowedExtension || Objects.requireNonNull(file.getOriginalFilename()).toLowerCase().endsWith(s);
requireNonNull тут не особо помогает

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +                isAllowedExtension = isAllowedExtension || Objects.requireNonNull(file.getOriginalFilename()).toLowerCase().endsWith(s);
Как минимум вынеси `file.getOriginalFilename().toLowerCase()` в переменную вне цикла

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +            }
Тут стримы приходят на помощь
```suggestion
            String name = file.getOriginalFilename().toLowerCase();
            boolean isAllowedExtension = mask.stream().anyMatch(m -> name.endsWith(m));
```

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +            final List<T> listB) {
final тут не спасёт от изменений

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    listA.size() + listB.size());
это в общем бесполезно

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +            result.addAll(listB);
```suggestion
            ArrayList<T> result = new ArrayList<>();
            if (listA != null) result.addAll(listA);
            if (listB != null) result.addAll(listB);
```

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    isTextFile = isTextFile || files[i].endsWith(s);
аналогично 
```suggestion
                boolean isTextFile = maskTextFile.stream().anyMatch(m -> files.[i].endsWith(m));
```
но вообще этот код дублируется, так что имеет смысл вынести в Utils

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    final ArrayList<String> mask = joinLists(maskPic, maskTextFile);
Чтобы ниже не делать циклов и стримов, можно поменять это на простые регулярки:
final String IS_TEXT_FILE = ".+\.(bib)|(tex)";
И дальше просто проверять filename.matches(IS_TEXT_FILE);

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    contents.add(i, Collections.singletonList("test/" + files[i]));
Если у тебя тут свежая джава, то:
```suggestion
                    contents.add(i, List.of("test/" + files[i]));
```

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +            return new FileList("shit happens", null, null, null);
Тут можешь бросить своё исключение
А вообще можешь и не ловить, ведь вернётся просто 500 ошибка
Более-менее удобно будет читать хоть из браузера, хоть из командной строки
А перед "продакшеном" сможешь просто навесить ErrorHandler (в другом комменте давал ссылку), и возвращать юзеру нормальную текстовую ошибку, и для себя куда-нибудь логгировать

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +        ArrayList<List<String>> contents = new ArrayList<>();
Не очень понимаю, зачем тут лист листов, если в обоих случаях ты тут кладёшь синглтоны

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/FileList.java
> +// Возможно, лучше сделать массив объектов, нежели объект содержащий несколько массивов с инфой о разных файлах
Да, это так

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/FileList.java
> +    // Определяю по сообщению всё ли хорошо на фронте
не надо так

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/CompilationResult.java
>      public String message;
соотв это убираешь, когда добавляешь кастомные эксепшены

2020-03-01 22:14 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/FileList.java
> +    public ArrayList<List<String>> contents;
Понимаю, что так пока что проще, но в будущем лучше фронту давать пути, а они пусть сами подгружают по ним файлы через ResourcesHandler по мере необходимости

2020-03-01 23:08 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/CompileController.java
> +        return new CompilationResult(compRet.contains("! LaTeX Error:") ? compRet : "ok", "test/test.pdf");
Пока что не хочется копаться в исключениях, тем более это не исключение, а результат компиляции, который отображается пользователю.

2020-03-01 23:13 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +            final List<T> listB) {
Это не мой код справедливости ради. Я никаких изменений в них не вношу, так что мне просто удалить final?

2020-03-01 23:17 UTC, Parol45 commented on src/main/java/ru/test/restservice/domain/FileList.java
> +    public ArrayList<List<String>> contents;
Тут фишка в том, что в проекте может быть несколько файлов и, чтобы не перегружать сервер, содержимое текстовых скидывается в локальные переменные js при загрузке страницы

2020-03-01 23:21 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +            result.addAll(listB);
:)

2020-03-02 00:14 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/CompileController.java
> +        return new CompilationResult(compRet.contains("! LaTeX Error:") ? compRet : "ok", "test/test.pdf");
Интересная механика кидания эксепшнов вне try catch. И работает ведь жесть какаята

2020-03-02 00:23 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +    final ArrayList<String> mask = joinLists(maskPic, maskTextFile);
Получается суть в том, чтобы в классах (Rest)Controller оставлять только методы с @Mapping?

2020-03-02 00:23 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +    final ArrayList<String> mask = joinLists(maskPic, maskTextFile);
Дебила какого-то упомянул случайно

2020-03-02 00:27 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +    final ArrayList<String> mask = joinLists(maskPic, maskTextFile);
И расскажи про разницу в написании в фулл капсе и camelCase

2020-03-02 01:16 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +            }
Почитаю про это, спасибо, но я решил регулярками

2020-03-02 01:19 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    listA.size() + listB.size());
¯\_(ツ)_/¯ стырил код. Он работал, так что решил даже не глядеть

2020-03-02 01:25 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    contents.add(i, Collections.singletonList("test/" + files[i]));
![image](https://user-images.githubusercontent.com/47885426/75638649-e4d2c480-5c3d-11ea-903c-fce262283e3f.png)

2020-03-02 01:28 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    contents.add(i, Collections.singletonList("test/" + files[i]));
А на такое он ругается
![image](https://user-images.githubusercontent.com/47885426/75638707-4f840000-5c3e-11ea-92f3-2d56128f87ca.png)

2020-03-02 01:30 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +        ArrayList<List<String>> contents = new ArrayList<>();
Нет, я в каждую ячейку внешнего листа кладу лист всех строк из файла

2020-03-02 01:30 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +        ArrayList<List<String>> contents = new ArrayList<>();
Не самая умная реализация класса - надо будет переделать, да

2020-03-02 01:31 UTC, Parol45 commented on src/main/java/ru/test/restservice/domain/FileList.java
> +    public ArrayList<List<String>> contents;
Добавлю в todo

2020-03-02 01:42 UTC, Parol45 commented on src/main/java/ru/test/restservice/domain/FileList.java
> +// Возможно, лучше сделать массив объектов, нежели объект содержащий несколько массивов с инфой о разных файлах
:(

2020-03-02 01:42 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    contents.add(i, Collections.singletonList("test/" + files[i]));
Сейчас всё равно удалю этот стыд

2020-03-02 02:11 UTC, Parol45 commented
Господин ревьюер, зацените также файлы в папке resources

2020-03-02 05:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompileController.java
> +        return new CompilationResult(compRet.contains("! LaTeX Error:") ? compRet : "ok", "test/test.pdf");
Есть checked и unchecked exceptions, если не путаю
Но в общем суть в том, что RuntimeException можно не отлавливать
А в спринге вообще нужно отлавливать только если это нормальная часть работы. А так просто всё пробрасываешь выше, а потом в ErrorHandler'е формируешь на основании ошибки запрос, который вернётся пользователю

2020-03-02 05:09 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    final ArrayList<String> mask = joinLists(maskPic, maskTextFile);
Кроме какого-то кода, общего между ними. И в методах контроллеров вообще стоит оставлять минимум кода — только вызывать всякие Service и Utils, и мб немного преобразовывать результат.

2020-03-02 05:12 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +                    contents.add(i, Collections.singletonList("test/" + files[i]));
Поставь jdk11 по приколу

2020-03-02 07:00 UTC, Donutellko reviewed
JS позже посмотрю

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +                pBuilder.command("sh", "-c", "pdflatex --synctex=1 --interaction=nonstopmode \"test.tex\"");
Раз уж добавил параметр, используй
```suggestion
                pBuilder.command("cmd.exe", "/c", "pdflatex --synctex=1 --interaction=nonstopmode \"" + filename + \"");
            } else {
                pBuilder.command("sh", "-c", "pdflatex --synctex=1 --interaction=nonstopmode \"" + filename + "\"");
```

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompilerController.java
> +        compileTexFile("");
```suggestion
        compileTexFile("text.tex");
```

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompilerController.java
> +        compileTexFile("");
ну и потом понятно переделать так, чтоб путь к файлу определялся по пользователю

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/FileService.java
> +    public final static String ALLOWED_FILE = TEXT_FILE.substring(0, TEXT_FILE.length() - 1)
не надо так. изменение в любой из двух регулярок её сломает
давай лучше перенесём это всё в FileUtils, создав три функции
```
boolean isTextFile(String name) { return name.matches(TEXT_FILE_REGEX); }
boolean isPicFile(String name) { return name.matches(PIC_FILE_REGEX); }
boolean isAllowedFile(String name) { return isTextFile(name) || isPicFile(name); }
```

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            }
Можно убрать проверку
```suggestion
            Files.createDirectories(Paths.get("test"));
```

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            Files.write(path, text.getBytes(StandardCharsets.UTF_8));
я не уверен, но вроде write() должен создать файл сам, если его нет

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +        }
в моём понимании если у тебя тут кинулся эксепшен, то дальше нет смысла в контроллере вызывать compileTexFile()
в общем можно убрать это
к тому же из Files вроде кидаются только IOException и мб какая-то ещё. Всё это закрывать общим Exception'ом не очень хорошо

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +        return result;
опять же всё в сервис
и опять же не нужно тут отлавливать ошибку

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +                throw new FileException("Wtf have u passed as file?");
рекомендуется всегда ставить фигурные скобки у if/else, как минимум если код не на той же строчке, что проверка

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
опять же всё в сервис
и опять же не нужно тут отлавливать ошибку

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +     */
Вот это очень классно будет описывать через Swagger. Если будет время/желание

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/CompilationResult.java
> +    // В случае успеха - путь до скомпилированного пдфника (может тогда и без объекта обойтись)
он у тебя пока что только в случае успеха передаётся
не, оставь пока что объект. наверняка здесь потом ещё другие вещи понадобится сообщать на фронт
например, компилятор tex'а вроде бы выдаёт какие-то warning'и

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/CompilationResult.java
> -    public String message;
Если среди вывода компилятора при успешной компиляции есть потенциально полезная информация, всё-таки давай будем его возвращать

2020-03-02 07:00 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/CompilationResult.java
>  import lombok.AllArgsConstructor;
этому классу на самом деле место в пакете dto

2020-03-02 13:22 UTC, Parol45 commented on src/main/java/ru/test/restservice/domain/CompilationResult.java
> -    public String message;
Я его и так возвращаю через message http пакета

2020-03-02 13:25 UTC, Parol45 commented on src/main/java/ru/test/restservice/domain/CompilationResult.java
> +    // В случае успеха - путь до скомпилированного пдфника (может тогда и без объекта обойтись)
Ладна

2020-03-02 13:39 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/FileService.java
> +    public final static String ALLOWED_FILE = TEXT_FILE.substring(0, TEXT_FILE.length() - 1)
Её не сломает, но твоё решение красивее, да

2020-03-02 14:13 UTC, Donutellko commented on src/main/java/ru/test/restservice/domain/CompilationResult.java
> -    public String message;
При успешной компиляции бывают ворнинги. Пользователю могут понадобиться

2020-03-02 14:15 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            Files.write(path, text.getBytes(StandardCharsets.UTF_8));
Да, так и есть. Я к решению с использованием Files не сразу пришёл.

2020-03-02 14:21 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +        }
Только IOException.
Теперь этот метод может бросить эксепшн, который обработается в try catch метода компиляции, но там тоже весь код покрыт try catch. Это тоже как-то стоит поменять?

2020-03-02 14:56 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +     */
Да, он мне понадобится ближе к концу диплома.
Как я понял, он документацию собирает вместе и красивую UI предоставляет

2020-03-03 06:22 UTC, Donutellko commented
А так в целом мне уже нравится

2020-03-03 06:23 UTC, merged