Saving files
Parol45/PolyTeX pull request #2
Opened 2020-03-03 23:06 UTC by Parol45

2020-03-03 23:06 UTC, Parol45 commented
Изменений в бэке немного

2020-03-04 06:38 UTC, Donutellko requested changes

2020-03-04 06:38 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +        RewriteFiles(files);
ммм, функция с большой буквы

2020-03-04 06:38 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +            // file = undefined ??? сработает ли ???
В смысле? 
И я вообще не вижу, где начинается этот if. Используй автоформатирование.

2020-03-04 06:38 UTC, Donutellko commented on src/main/resources/templates/index.html
> +</div><!--между этими тегами не должно быть ничего--><div class="main-panel" id="source-wrap" contenteditable oninput="angular.element(this).scope().saveOpenedDocLocally()">
oninput происходит при каждом изменении, с большими файлами будет жопа. Есть onchange, который происходит при потере фокуса на элементе после изменения.

2020-03-04 06:38 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
>      public ArrayList<FileItemDTO> returnFileList() throws IOException {
Всё ещё "Объект с тремя списками"

2020-03-04 06:38 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    @PostMapping("/save-file")
Вообще, если следовать рекомендациям по REST, по идее должно быть так:
GET /files - получение списка файлов
POST /files - создание и сохранение нового файла
PUT /files - сохранение существующего файла
POST или PUT имхо пофиг, но /save-file лучше поменять, тем более это в единственном числе, а ты передаёшь список

2020-03-04 06:38 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
>  @RequestMapping("/api")
saveAndReturnFile() имхо можно назвать просто save()
и сделай не статическим

2020-03-04 06:38 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
>          return listFiles("test");
тоже сделай не статическим, а FileService инжекть через конструктор (добавь поле private final FileService fileService и аннотацию @ RequiredArgsConstructor)

2020-03-04 06:38 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +                () => {
круто

2020-03-04 06:38 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +            angular.forEach($scope.files, (value, key) => {
лямбду лучше вынести отдельную функцию

2020-03-04 06:38 UTC, Donutellko commented on src/main/resources/templates/index.html
> +</div><!--между этими тегами не должно быть ничего--><div class="main-panel" id="source-wrap" contenteditable oninput="angular.element(this).scope().saveOpenedDocLocally()">
вижу, ты уже использовал onchange выше. Если возникали проблемы, можешь добавить сохранение файла при клике на открытие другого и на другие действия, которые могут привести к потере текущего содержимого

2020-03-05 16:46 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +            // file = undefined ??? сработает ли ???
Я пытался после события onchange очистить выбранный файл в input. Часа два потратил, но не вышло.
А if в этой функции один

2020-03-05 16:49 UTC, Parol45 commented on src/main/resources/templates/index.html
> +</div><!--между этими тегами не должно быть ничего--><div class="main-panel" id="source-wrap" contenteditable oninput="angular.element(this).scope().saveOpenedDocLocally()">
Есть ли какое-то событие для закрытия вкладки?

2020-03-05 16:52 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                () => {
А что сделать?

2020-03-05 16:57 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +    @PostMapping("/save-file")
Это намёк, что стоит прочитать про виды http запросов?

2020-03-05 16:58 UTC, Parol45 commented on src/main/resources/templates/index.html
> +</div><!--между этими тегами не должно быть ничего--><div class="main-panel" id="source-wrap" contenteditable oninput="angular.element(this).scope().saveOpenedDocLocally()">
Да, onchange не работает на div. Но как ты это увидел? Экстрасенс?

2020-03-05 17:16 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    @PostMapping("/save-file")
мб намёк, мб нет, но в общем почитай)
не совсем про виды, а про REST и рекомендации по именованию

2020-03-05 17:23 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +                () => {
имхо, было бы классно показывать это где-то
а так имхо красивее будет сделать так: $http.post('...', (response) => if (response.code != 200) alert(response.data.message)}
но тут как хочешь

2020-03-05 17:25 UTC, Donutellko commented on src/main/resources/templates/index.html
> +</div><!--между этими тегами не должно быть ничего--><div class="main-panel" id="source-wrap" contenteditable oninput="angular.element(this).scope().saveOpenedDocLocally()">
тогда сделай сохранение при клике на отправку и на смену файла
и вместо onchange ещё есть onblur

2020-03-05 17:30 UTC, Parol45 commented on src/main/resources/templates/index.html
> +</div><!--между этими тегами не должно быть ничего--><div class="main-panel" id="source-wrap" contenteditable oninput="angular.element(this).scope().saveOpenedDocLocally()">
Эти два уже сделал. Осталось только при закрытии вкладки

2020-03-05 20:21 UTC, Parol45 commented
Я исправил всё, что смог, мой любимый староста.

2020-03-09 07:30 UTC, Donutellko requested changes

2020-03-09 07:30 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompilerController.java
> +    private final CompilerService compilerService = new CompilerService();
убираешь отсюда инициализацию и пишешь @RequiredArgsConstructor над классом

2020-03-09 07:30 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    private final FileService fileService = new FileService();
аналогично
если ты написал @ Service, то это стало бином, и Спринг сам его создаст и передаст тебе сюда, как только создашь конструктор, через который его инициализируешь с помощью @RequiredArgs

2020-03-09 07:30 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +        return new ResponseEntity<>(HttpStatus.OK);
можно сделать void

2020-03-09 07:30 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompilerController.java
> +    private final CompilerService compilerService = new CompilerService();
почему я все еще вижу инициализацию?

2020-03-09 11:19 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/CompilerController.java
> +    private final CompilerService compilerService = new CompilerService();
Потому что я эту аннотацию сервисам добавил давным давно, увидел её и подумал, что больше и не нада. А без инициализации ошибкой подчёркивает

2020-03-09 11:25 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +    private final FileService fileService = new FileService();
Но я всё же недопонял в чём разница в итоге.
Эта аннотация по идее заменяет то, что я написал конструктор: "@RequiredArgsConstructor генерирует конструктор с 1 параметром для каждого поля, которое требует специальной обработки."

2020-03-09 11:32 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +    private final FileService fileService = new FileService();
А для инжекта есть отдельная аннотации @Inject или @Autowired, которые непонятно что делают

2020-03-09 12:26 UTC, Parol45 commented on src/main/java/ru/test/restservice/api/FileController.java
> +    private final FileService fileService = new FileService();
Но я поменял. Аннотации - красиво

2020-03-09 19:48 UTC, Donutellko requested changes

2020-03-09 19:48 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    private final FileService fileService = new FileService();
```suggestion
    private final FileService fileService;
```

2020-03-09 19:48 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileController.java
> +    @GetMapping("/file-list")
```suggestion
    @GetMapping("/files")
```

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +            $http.post("/api/compile/", sourceArea.innerText.replace(/\n\n/g, "\n")).then(
реплейс для чего?

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +                    $scope.error();
имхо лучше назвать showError, например

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
>                  alert("Bad file");
тут тоже пусть будет вызов $scope.error("Bad file")

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +                        $scope.error();
почему ты так упорно не хочешь сделать так?
```
                    (response) => {
                        $scope.error(response.data.message);
```

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +            angular.forEach($scope.files, (value, key) => {
не вынес, не ответил и пометил как resolved
не делай так

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +            angular.forEach($scope.files, (value, key) => {
но выносить на самом деле уже не имеет смысла, да, потому что кода стало меньше

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +                    if ($scope.files[i].name === name) {
поиск в массиве делается так: let index = $scope.files.find((file) => file.name === name));
но имхо искать по имени плохая идея, если только имя не включает в себя весь путь

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +                        }
что происходит тут я не понимаю

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
>              // Нахождение в списке по значению слишком сложное, так что обхожу все
чем find не устроил?

2020-03-09 19:48 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
>              // Нахождение в списке по значению слишком сложное, так что обхожу все
и не очень понимаю, что ниже

2020-03-09 19:49 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +            $http.post("/api/compile/", sourceArea.innerText.replace(/\n\n/g, "\n")).then(
innerText один перенос строки возвращает как два

2020-03-09 19:51 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +            angular.forEach($scope.files, (value, key) => {
Но вынес же

2020-03-09 19:52 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +            angular.forEach($scope.files, (value, key) => {
![image](https://user-images.githubusercontent.com/47885426/76251729-96827e80-6258-11ea-8279-dcde60af24bd.png)

2020-03-09 19:54 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +            angular.forEach($scope.files, (value, key) => {
А, окей, отлично

2020-03-09 19:55 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                        $scope.error();
Я коды этих ответов всё равно буду в консоли смотреть

2020-03-09 19:55 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                        $scope.error();
наверное

2020-03-09 19:55 UTC, Donutellko requested changes

2020-03-09 19:55 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +        $http.get("/api/file-list/").then(
Соответственно
```suggestion
        $http.get("/api/files/").then(
```

2020-03-09 20:01 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                    if ($scope.files[i].name === name) {
Будет включать

2020-03-09 20:02 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                        }
Если удалить документ с индексом меньше, чем у открытого, то его надо сдвинуть
Если удаляется открытый документ то очищаю поле ввода и сигнализирую, что сейчас нет открытого документа

2020-03-09 20:06 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                        $scope.error();
И при потере соединения data будет null

2020-03-09 20:12 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                        $scope.error();
Да и пока что нет единого интерфейса для возврата инфы об ошибках. Так что это пока что просто заглушка. У меня половина проекта так

2020-03-09 20:18 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
>              // Нахождение в списке по значению слишком сложное, так что обхожу все
У меня раньше было три списка, а не список объектов, вот и занимался подобным

Случайно начал ревью лол

2020-03-09 20:24 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
>              // Нахождение в списке по значению слишком сложное, так что обхожу все
При смене открытого документа я сохраняю его содержимое в saveOpenedDocLocally
Меняю индекс открытого документа
И printFile - вывожу в область содержимое нового файла

Я опять нажал ревью. В файлах неудобно комментить.

ЖОПА сколько раз я нажал на ревью

2020-03-09 20:26 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                        $scope.error();
Я там оставил TODO. Не забуду

2020-03-09 20:29 UTC, Parol45 commented on src/main/resources/static/src/ask_compile.js
> +                    if ($scope.files[i].name === name) {
Пока что имена, потому что всё в одной папке

2020-03-10 06:30 UTC, Donutellko approved these changes

2020-03-10 06:31 UTC, merged