Dev №5
Parol45/PolyTeX pull request #5
Opened 2020-03-25 12:13 UTC by Parol45

2020-03-26 22:05 UTC, Donutellko requested changes
Нужно избавиться от `projectBasePath`

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/WebSecurityConfig.java
> +                .antMatchers("/","/api/**", "/projects").hasAnyRole("USER", "ADMIN")
тут не /projects/** ?

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/WebSecurityConfig.java
> +                .antMatchers("/","/api/**", "/projects").hasAnyRole("USER", "ADMIN")
Кстати, очень советую начать писать тесты. Вот прям очень-очень советую.
В них довольно удобно проверять уровни доступа. Типа обращаешься к эндпоинту с разными правами проверяешь, что тебе вернулось 403 или не 403.

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompilerController.java
> +        FileItemDTO file = files.stream().filter(f -> targetFilepath.equals(f.path)).findFirst().get();
такое не стоит писать в одну строчку
```suggestion
        FileItemDTO file = files.stream()
                .filter(f -> targetFilepath.equals(f.path))
                .findFirst().get();
```

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
> +    List<Project> findOwnedProjects(User user);
По идее ты можешь убрать `@Query` и сделать так: `findAllByOwnersContains()`

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
> +    List<Project> findOwnedProjects(User user);
Правда, так может возникнуть "проблема n+1 запроса" или как-то так называется.

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
> +    List<Project> findOwnedProjects(User user);
А DISTINCT вроде не нужен
И слово SELECT тоже можно тут опускать

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/dto/FileItemDTO.java
> -    // Содержимое файла (список строк) - сменить на filePath
путь добавил, но content оставил?

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/entity/Project.java
> +        return "Project(id = " + id + ", name = " + name + ", path = " + path +")";
Куда ты это выводишь и чем тебе не угодил toString, генерируемый ломбоком с аннотацией Data?

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/entity/Project.java
> +    @JoinTable
`@JoinTable can be used to map following associations to database table: bidirectional many-to-one/one-to-many, unidirectional many-to-one, and one-to-one (both bidirectional and unidirectional) associations.`
Эта аннотация не для many-to-many

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
тут не должен быть нужен `= null`
И по-моему хибернейт умеет вызывать только конструкторы без аргументов и сетить каждое значение. Ты уже пробовал доставать объекты пользователей из БД?

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/entity/User.java
> +    @JsonIgnore
Ты не должен передавать энтити никуда. Если не передаёшь, убери аннотацию

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
>      // TODO: после добавления авторизации связать компиляцию с рабочей папкой и компилировать по filename
тудушка уже не нужна?

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +    private final ProjectController projectController;
сервис не может обращаться к контроллеру

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectBasePath = projectRepository.findById(projectId).path;
То есть все пользователи на сайте работают только с одним проектом.

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            pBuilder.directory(new File(projectController.projectBasePath + file.path.replaceAll(file.name + "$", "")));
для получения пути до директории есть более адекватные  способы
ну и про projectBasePath уже написал

2020-03-26 22:05 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectBasePath = projectRepository.findById(projectId).path;
Понимаю, что это типа временное, но давай ты сразу сделаешь по-человечески

2020-03-26 23:48 UTC, Parol45 commented on src/main/java/ru/test/restservice/WebSecurityConfig.java
> +                .antMatchers("/","/api/**", "/projects").hasAnyRole("USER", "ADMIN")
Работает и так, как написано. Хз в чём разница.
Тесты надо учица писать да

2020-03-26 23:59 UTC, Parol45 commented on src/main/java/ru/test/restservice/WebSecurityConfig.java
> +                .antMatchers("/","/api/**", "/projects").hasAnyRole("USER", "ADMIN")
Исправил на всякий случай

2020-03-27 00:01 UTC, Parol45 commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
> +    List<Project> findOwnedProjects(User user);
Отношение проектов к пользователям - многие ко многим, так что дистинкт нужен.
Запрос же вроде эффективный, зочем его менять

2020-03-27 00:03 UTC, Parol45 commented on src/main/java/ru/test/restservice/dto/FileItemDTO.java
> -    // Содержимое файла (список строк) - сменить на filePath
Да. Текстовые файлы тут не будут здоровенными. Если пользователь получит всё сразу или потом дозагрузит - разницы не будет практически

2020-03-27 00:05 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/Project.java
> +        return "Project(id = " + id + ", name = " + name + ", path = " + path +")";
Я в отладку как-то заходил и там писало ошибку в методе toString связанную с полем owners. Что не может преобразовать в string. Вот я на всякий случай явно прописал

2020-03-27 00:06 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/Project.java
> +    @JoinTable
В гайде на баелдунг её использовали тем не менее

2020-03-27 00:07 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
![image](https://user-images.githubusercontent.com/47885426/77708061-0eca9d00-6fd8-11ea-8713-ad600522f29d.png)

2020-03-27 00:10 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
Пробовал. Всё норм
![image](https://user-images.githubusercontent.com/47885426/77708183-610bbe00-6fd8-11ea-85a7-fa7d4ffd25c3.png)
Если уберу - пишет ошибку. Если убрать final - будет требовать в конструкторе
![image](https://user-images.githubusercontent.com/47885426/77708134-41749580-6fd8-11ea-9f34-57b48d3be796.png)

2020-03-27 00:11 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    @JsonIgnore
Бебебебе

Убрал

2020-03-27 00:12 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    @JsonIgnore
Зачем отдельный класс для этого создавать, если у сущности уже есть все нужные поля

2020-03-27 00:12 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
>      // TODO: после добавления авторизации связать компиляцию с рабочей папкой и компилировать по filename
Это да

2020-03-27 00:13 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +    private final ProjectController projectController;
Как видишь, может. Я не знаю чем тебе не угодил projectBasePath и как сделать иначе

2020-03-27 00:14 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +    private final ProjectController projectController;
Ладно, знаю

2020-03-27 00:15 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectBasePath = projectRepository.findById(projectId).path;
А разве это не бин, который у каждого пользователя свой?

2020-03-27 00:17 UTC, Parol45 commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
> +    List<Project> findOwnedProjects(User user);
Я тут подумал, дистинкт не нужен, да

2020-03-27 00:18 UTC, Parol45 commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
> +    List<Project> findOwnedProjects(User user);
SELECT не уберу

2020-03-27 00:40 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectBasePath = projectRepository.findById(projectId).path;
Я про контроллер

2020-03-27 02:21 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectBasePath = projectRepository.findById(projectId).path;
Теперь прочитал про bean scopes

2020-03-27 03:28 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            pBuilder.directory(new File(projectController.projectBasePath + file.path.replaceAll(file.name + "$", "")));
Какъ

2020-03-27 03:30 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            pBuilder.directory(new File(projectController.projectBasePath + file.path.replaceAll(file.name + "$", "")));
Вот такой?
`Paths.get(file.path).getParent()`

2020-03-27 03:37 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
А, или ты о том, что не нужен AllArgsConstructor

2020-03-27 03:41 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            pBuilder.directory(new File(projectController.projectBasePath + file.path.replaceAll(file.name + "$", "")));
И ещё вопрос. Стоит ли из ProjectConroller вообще выносить тела функций в ProjectService?
Они там не такие уж и многострочные

2020-03-27 05:21 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
Даже так ему не нравится
![image](https://user-images.githubusercontent.com/47885426/77724398-f1132d00-7003-11ea-911e-ba7b162c2c76.png)

2020-03-27 05:44 UTC, Parol45 commented
projectBasePath убрал, создав свою версию UserDetails и добавив туда поле.
Теперь получаю путь к проекту через Authentication

2020-03-27 05:44 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/Project.java
> +        return "Project(id = " + id + ", name = " + name + ", path = " + path +")";
Убрал

2020-03-27 08:17 UTC, Donutellko requested changes

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
Если у тебя есть final, то не должно быть NoArgsConstructor. Убери эту аннотацию, убери инициализацию

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/Client.java
> +    public Client(String username, String password, Collection<? extends GrantedAuthority> authorities) {
Если у тебя есть ломбок, тебе в большинстве случаев не надо писать конструкторы
Можешь сделать эти три поля final. `@Data` содержит в себе `@RequiredArgsConstructor`, так что точно такой же создастся сам.

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +        Authentication auth = SecurityContextHolder.getContext().getAuthentication();
стрёмно

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +            client.selectedProject = project;
стрёмно

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/CompilerApiController.java
>      @PostMapping("/compile")
```suggestion
    @PostMapping("/projects/{projectId}/compile")
```

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +    @GetMapping("/delete-project")
```suggestion
    @GetMapping("/projects/{projectId}/delete")
```

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectRepository.delete(projectToDelete);
логики не должно быть в контроллере

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectRepository.delete(projectToDelete);
и во всех остальных методах контроллера

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileApiController.java
>      @GetMapping("/files")
```suggestion
    @GetMapping("/projects/{projectId}/files")
```

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileApiController.java
>      public void deleteFile(@RequestParam String path) throws IOException {
@DeleteMapping("/projects/{projectId}/files")

2020-03-27 08:17 UTC, Donutellko commented on src/main/java/ru/test/restservice/api/FileApiController.java
> +    @PutMapping("/new-file")
```suggestion
    @PostMapping("/projects/{projectId}/files/")
```
И это объединить с перезаписью
По идее тебе вообще разницы никакой не будет -- создать или перезаписать

2020-03-27 09:59 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
![image](https://user-images.githubusercontent.com/47885426/77744529-cc7e7b80-702a-11ea-8f89-5a04a1d2480e.png)

2020-03-27 10:01 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectRepository.delete(projectToDelete);
Смысл выносить 3 строки кода в другой метод

2020-03-27 10:09 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectRepository.delete(projectToDelete);
В этом три, в других 4-7

2020-03-27 10:10 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectRepository.delete(projectToDelete);
Правило простое: логика в сервисах, в контроллерах вызов сервисов.

2020-03-27 10:12 UTC, Donutellko commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
Ладно, но зачем вообще final?

2020-03-27 10:12 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +        projectRepository.delete(projectToDelete);
Окей

2020-04-01 12:25 UTC, Parol45 commented on src/main/java/ru/test/restservice/entity/User.java
> +    final private UUID user_id = null;
Поля с final lombok в конструктор не включает. Я при регистрации создаю новый объект этого типа, чтобы сунуть в репозиторий. Не хочу там генерировать id, если для этого есть специальная аннотация внутри класса

2020-04-04 12:07 UTC, Donutellko requested changes

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +                biber = "biber.exe \"" + file.name.replaceAll("\\.tex$", "") + "\"",
рекомендую String.format:
```suggestion
                pdfLaTeX = String.format("pdflatex --synctex=1 --interaction=nonstopmode \"%s\"", file.name),
                biber = String.format("biber.exe \"%s\" ", file.name.replaceAll("\\.tex$", "")),
```
И скорее всего терминал хавает одинарные кавычки:
```suggestion
                pdfLaTeX = String.format("pdflatex --synctex=1 --interaction=nonstopmode '%s' ", file.name),
                biber = String.format("biber.exe '%s' ", file.name.replaceAll("\\.tex$", "")),
```

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +        if (Files.exists(Paths.get(project.path + file.path.replaceAll("\\.tex$", ".bcf")))) {
оч сложная для понимания строка, вынеси из скобок в переменную

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +            message = message + "\n" + executeTerminalCommand(biber, pathToFile);
мб имеет смысл это в два отдельных поля в ДТО запихнуть?

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
>      Project findById(UUID id);
В первой строчке у тебя ключом указан Long, а во второй UUID

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/dao/ProjectRepository.java
>      Project findById(UUID id);
и findById это дефолтный метод

2020-04-04 12:07 UTC, Donutellko commented on src/main/resources/static/src/ask_compile.js
> +                sourceArea.innerHTML = "<div><img src='" + file.content[0] + "' alt='" + file.content[0] +"'></div>";
```suggestion
                sourceArea.innerHTML = `<div><img src='${file.content[0]}' alt='${file.content[0]}'></div>`;
```

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +    }
Это точно должно быть в Controller, а не в RestController?

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +        ModelAndView projs = new ModelAndView("redirect:/projects");
1) сервис не знает про маппинги, он не может возвращать ModelAndView
2) по хорошему это должно делаться рест-запросом

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +        ModelAndView projs = new ModelAndView("redirect:/projects");
аналогично

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
>      public ModelAndView openProject(UUID projectId, Authentication auth) {
имхо сервис не должен знать про аутентификацию

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +            ModelAndView main = new ModelAndView("index");
и аналогично сервис не должен знать про страницы
и имхо этот метод вообще не должен существовать, опиши мне, как происходит открытие проекта

2020-04-04 12:07 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +                        .findAll()
я бы это не переносил на новую строчку, но дело вкуса
```suggestion
                projectRepository.findAll()
```

2020-04-04 12:08 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +                biber = "biber.exe \"" + file.name.replaceAll("\\.tex$", "") + "\"",
С двойными норм робит

2020-04-04 12:10 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/CompilerService.java
> +                biber = "biber.exe \"" + file.name.replaceAll("\\.tex$", "") + "\"",
и с одинарными, скорее всего
не хочешь проверять -- окей, но String.format имеет смысл использовать

2020-04-04 12:30 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +    }
Про rest, забыл

2020-04-04 12:33 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +    }
Ну вообще тут спорно. Разве rest контроллеры не для ajax?

2020-04-04 12:35 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +    }
Rest контроллеры могут возвращать view?

2020-04-04 13:17 UTC, Parol45 commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +            ModelAndView main = new ModelAndView("index");
Проекту надо в жс передать id из аутентификации и проверить есть ли вообще у пользователя права на него

2020-04-04 13:48 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +            ModelAndView main = new ModelAndView("index");
в сервисе пусть будет метод проверитьПрава, а в контроллере будет просто
`если (проверитьПрава) вернуть моделЭндВью`

2020-04-04 13:50 UTC, Donutellko commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +    }
вот я тебе и предлагаю использовать аджакс:
`DELETE /projects/{projectId}/owners?email=`

2020-04-04 13:54 UTC, Parol45 commented on src/main/java/ru/test/restservice/web/ProjectController.java
> +    }
Так я не хочу это делать. У меня страница форму отправляет, иначе придётся js подключать. Это пока не важно

2020-04-04 15:15 UTC, Donutellko approved these changes

2020-04-04 15:15 UTC, Donutellko commented on src/main/java/ru/test/restservice/service/ProjectService.java
> +        Optional<Project> project = projectRepository.findById(projectId);
```suggestion
        Project project = projectRepository.findById(projectId)
             .orElseThrow(NotFoundException::new)
```
можно вот так сделать
и для user тоже

2020-04-04 15:18 UTC, merged